<?php
use Drupal\format_strawberryfield_facets\BlockDataAttributesRestorer;
function format_strawberryfield_facets_facets_search_api_query_type_mapping_alter($backend_plugin_id, array &$query_types) {
  if ($backend_plugin_id == 'search_api_solr') {
    $query_types['date_range'] = 'search_api_sbf_date_range';
  }
}

/**
 * Implements hook_block_view_alter().
 */
function format_strawberryfield_facets_block_view_alter(array &$build, \Drupal\Core\Block\BlockPluginInterface $block) {
  if ($block->getBaseId() === 'facets_summary_block') {
    $build['#pre_render'][] = [BlockDataAttributesRestorer::class, 'alterBlockWrapper'];
  }

}