<?php
/**
 * @file
 * Contains formater_strawberryfield.module.
 */

/**
 * Implements hook_page_attachments().
 *
 * Adds the quickedit library to the page for any user who has the 'access
 * in-place editing' permission.
 */
function format_strawberryfield_page_attachments(array &$page) {
    /*if (!\Drupal::currentUser()->hasPermission('access search')) {
        return;
    @TODO discuss if we need to limit viewers to a particular role?
    Could be nice to allow annotations as a drop replacement
    of the same viewer dependant on the rol
    }*/

    // Remove IIIF on admin routes, why make peoples life more complicated
    if (\Drupal::service('router.admin_context')->isAdminRoute()) {
        return;
    }
    $page['#attached']['library'][] = 'format_strawberryfield/iiif_openseadragon';
    $page['#attached']['library'][] = 'format_strawberryfield/iiif_openseadragon_strawberry';
}


/**
 * Implements hook_theme().
 */
function format_strawberryfield_theme() {
  return array(
    'remote_iiif_style' => array(
      'variables' => array(
        'style_name' => NULL,
        'path' => NULL,
        'width' => NULL,
        'height' => NULL,
        'alt' => '',
        'title' => NULL,
        'attributes' => array(),
      ),
    ),
  );
}
