<?php
/**
 * @file
 * Contains formater_strawberryfield_views.module.
 */

use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Template\Attribute;
use Drupal\Component\Utility\Html;
use Drupal\views\ViewExecutable;
use Drupal\views\Plugin\views\query\QueryPluginBase;
use Drupal\Core\Block\BlockPluginInterface;
use Drupal\search_api\Entity\Index;
use Drupal\search_api\Query\QueryInterface;
use Solarium\Component\ComponentAwareQueryInterface;
use Solarium\Core\Query\QueryInterface as SolariumQueryInterface;

/**
 * Implements hook_theme().
 */
function format_strawberryfield_views_theme($existing, $type, $theme, $path) {
  return [
    'format_strawberryfield_views_leaflet' => [
      'variables' => [],
      'template' => 'format-strawberryfield-views-leaflet',
      'render element' => 'elements',
    ],
  ];
}
/**
 * Prepares variables for the Format Strawberry Fields Leaflet Views style template.
 *
 * Default template: format-strawberryfield-views-leaflet.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - view: A ViewExecutable object.
 *   - rows: The row data that will contain Drupal Entities.
 *   - options: The Views/Views Style configured option.
 */
function template_preprocess_format_strawberryfield_views_leaflet(array &$variables) {
  $view = $variables['view'];
  $variables['view']->style_plugin->options;
  $geojsons = [];
  $geojsonsgrouped = [];
  if (!empty($variables['options']['leaflet_options']['metadataexposeentity_source'])) {
    /* @var $entity \Drupal\format_strawberryfield\Entity\MetadataExposeConfigEntity */
    $entity = \Drupal::entityTypeManager()->getStorage(
      'metadataexpose_entity'
    )->load(
      $variables['options']['leaflet_options']['metadataexposeentity_source']
    );
    if ($entity) {
      foreach ($variables['rows']['ungrouped'] ?? [] as $views_result_entity_uuid) {
        $url = $entity->getUrlForItemFromNodeUUID(
          $views_result_entity_uuid, TRUE
        );
        $geojsons[$views_result_entity_uuid] = $url;
      }
      foreach ($variables['rows']['grouped'] ?? [] as $group => $views_result_entity_uuids) {
        foreach ($views_result_entity_uuids as $views_result_entity_uuid) {
          $url = $entity->getUrlForItemFromNodeUUID(
            $views_result_entity_uuid, TRUE
          );
          $geojsonsgrouped[$group][] = $url;
        }
      }
    }
  }
  // Tried base64 but that expands 3 bytes into 4. Means it grows.
  $geojsons = json_encode($geojsons);
  $geojsonsgrouped = json_encode($geojsonsgrouped);
  $max_width = $variables['options']['leaflet_options']['max_width'];
  $max_width_css = empty($max_width) || $max_width == 0 ? '100%' : $max_width .'px';
  $max_height = $variables['options']['leaflet_options']['max_height'];

  // get the URL to our Metadata Expose Endpoint, we will get a string here.
  // Set a unique id attribute for the timeline embed div.  Also set a width and
  // height for the div.  This is required for proper styling of the timeline.
  // See https://timeline.knightlab.com/docs/instantiate-a-timeline.html.
  $htmlid = Html::getId('format_strawberryfield_views_leaflet_' . $view->storage->id() . '_' . $view->current_display);
  $variables['#attached']['drupalSettings']['format_strawberryfield_views']['leaflet'][$htmlid]['geojsonurls'] = $geojsons;
  $variables['#attached']['drupalSettings']['format_strawberryfield_views']['leaflet'][$htmlid]['geojsongroupedurls'] = $geojsonsgrouped;
  $variables['#attached']['drupalSettings']['format_strawberryfield_views']['leaflet'][$htmlid]['geojsonother'] =  [];
  $variables['#attached']['drupalSettings']['format_strawberryfield_views']['leaflet'][$htmlid]['width'] = $max_width_css;
  $variables['#attached']['drupalSettings']['format_strawberryfield_views']['leaflet'][$htmlid]['height'] = max(
    $max_height,
    480
  );
  $variables['#attached']['drupalSettings']['format_strawberryfield_views']['leaflet'][$htmlid]['maxzoom'] =$variables['options']['leaflet_options']['max_zoom'];
  $variables['#attached']['drupalSettings']['format_strawberryfield_views']['leaflet'][$htmlid]['minzoom'] =$variables['options']['leaflet_options']['min_zoom'];
  $variables['#attached']['drupalSettings']['format_strawberryfield_views']['leaflet'][$htmlid]['initialzoom'] =$variables['options']['leaflet_options']['initial_zoom'];

  $variables['#attached']['drupalSettings']['format_strawberryfield_views']['leaflet'][$htmlid]['tilemap_url'] =$variables['options']['leaflet_options']['tilemap_url'];
  $variables['#attached']['drupalSettings']['format_strawberryfield_views']['leaflet'][$htmlid]['tilemap_attribution'] =$variables['options']['leaflet_options']['tilemap_attribution'];
  $variables['#attached']['library'][] = 'format_strawberryfield_views/leaflet_strawberry_views';


  $style = 'width: ' . $max_width_css . '; height: ' . $max_height . ';';
  $variables['attributes'] = new Attribute(['id' => $htmlid, 'style' => $style, 'data-iiif-infojson' => '',  'class' => [
    'strawberry-leaflet-views-item',
    'leafletViewer',
    'field-iiif',
    'container',
  ]
  ]);
  unset($variables['rows']);
}

/**
 * Alter the query before it is executed.
 *
 * @param \Drupal\views\ViewExecutable $view
 *   The view object about to be processed.
 * @param \Drupal\views\Plugin\views\query\QueryPluginBase $query
 *   The query plugin object for the query.
 *
 * @see hook_views_query_substitutions()
 * @see \Drupal\views\Plugin\views\query\Sql
 */
function format_strawberryfield_views_views_query_alter(ViewExecutable $view, QueryPluginBase $query) {
  // Remove HOCR highlighter in the presence of a Views
  // Leaflet Display to avoid Solr errors
  if ($query->getPluginId() == 'search_api_query' && $view->getStyle()->getPluginId() == 'format_strawberryfield_views_leaflet') {
    $query->setOption('ocr_highlight', 'off');
  }
}

/**
 * Implements hook_block_view_BASE_BLOCK_ID_alter() for 'views_exposed_filter_block_sbf'.
 */
function format_strawberryfield_views_block_view_views_exposed_filter_block_sbf_alter(array &$build, BlockPluginInterface $block) {
  if ($block->getBaseId() == 'views_exposed_filter_block_sbf') {
    $build['#pre_render'][] = 'Drupal\format_strawberryfield_views\Plugin\Block\ViewsExposedFilterBlockModal::preRender';
  }
}

/**
 * Implements hook_views_data_alter().
 */
function format_strawberryfield_views_views_data_alter(array &$data) {
  //@see search_api_views_data()
  /** @var \Drupal\search_api\IndexInterface $index */
  foreach (Index::loadMultiple() as $index) {
    try {
      $key = 'search_api_index_' . $index->id();
      $table = &$data[$key];
      $advanced_fulltext_field = _search_api_views_find_field_alias('sbf_advanced_search_api_fulltext', $table);
      $table[$advanced_fulltext_field] = [
        'title'  => t('Advanced Fulltext search'),
        'group' => t('Search'),
        'help' => t('Search several or all fulltext fields at once allowing also multiple operator separated entries'),
        'filter' => [
          'title' => t('Advanced Fulltext search'),
          'field' => 'id',
          'id'    => 'sbf_advanced_search_api_fulltext',
        ],
      ];
      if ($advanced_fulltext_field != 'sbf_advanced_search_api_fulltext') {
        $table[$advanced_fulltext_field]['real field'] = 'sbf_advanced_search_api_fulltext';
      }
      // @TODO add also an argument ID if relationships are enabled to
      // $table[$advanced_fulltext_field]['argument']['id'] = 'sbf_advanced_search_api_fulltext';
      // Requires a special Argument Plugin. Not needed right now.
    }
    catch (\Exception $e) {
      $args = [
        '%index' => $index->label(),
      ];
      watchdog_exception('format_strawberryfield_views', $e, '%type while computing Views data for index %index: @message in %function (line %line of %file).', $args);
    }
  }
  return $data;
}


/**
 * Finds an unused field alias for a field in a Views table definition.
 *
 * @param string $field_id
 *   The original ID of the Search API field.
 * @param array $table
 *   The Views table definition.
 *
 * @return string
 *   The field alias to use.
 */
function _format_strawberryfield_views_find_field_alias($field_id, array &$table) {
  $base = $field_alias = preg_replace('/[^a-zA-Z0-9]+/S', '_', $field_id);
  $i = 0;
  while (isset($table[$field_alias])) {
    $field_alias = $base . '_' . ++$i;
  }
  return $field_alias;
}


/**
 * Implements hook_search_api_solr_query_alter().
 *
 * Let modules alter the Solarium select query before executing it.
 *
 * After this hook, the select query will be finally converted into an
 * expression that will be processed by the lucene query parser. Therefore you
 * can't modify the 'q' parameter here, because it gets overwritten by that
 * conversion. If you need to modify the 'q' parameter you should implement an
 * event listener instead of this hook that handles the solarium events (our
 * connector injects the drupal event handler into solarium) or implement
 * hook_search_api_solr_converted_query() instead. If you want to force a
 * different parser like edismax you must set the 'defType' parameter
 * accordingly.
 */
function format_strawberryfield_views_search_api_solr_converted_query_alter(SolariumQueryInterface $solarium_query, QueryInterface $query) {
  // To get a list of solarium events:
  // @see http://solarium.readthedocs.io/en/stable/customizing-solarium/#plugin-system
  if ($query->getOption('sbf_advanced_search_filter')) {
    $components = $solarium_query->getComponents();
    if (isset($components['edismax'])) {
      $solarium_query->removeComponent(ComponentAwareQueryInterface::COMPONENT_EDISMAX);
      $solarium_query->addParam('defType','lucene');
    }
  }
}

/**
 * Implements hook_library_info_alter().
 */
function  format_strawberryfield_views_library_info_alter(&$libraries, $module) {
  // Update imaginary library 'foo' to version 2.0.
  if ($extension === 'facets' && isset($libraries['drupal.facets.views-ajax'])) {

      $libraries['drupal.facets.views-ajax']['version'] = '1.x';

      // To accurately replace library files, the order of files and the options
      // of each file have to be retained; e.g., like this:
      $old_path = '/js';

      // Since the replaced library files are no longer located in a directory
      // relative to the original extension, specify an absolute path (relative
      // to DRUPAL_ROOT / base_path()) to the new location.
      $new_path = '/' . \Drupal::service('extension.list.module')
          ->getPath('format_strawberryfield_views') . '/js';
      $new_js = [];
      $replacements = [
        $old_path . '/facets-views-ajax.js' => $new_path . '/facets-views-ajax.js',
      ];
      foreach ($libraries['drupal.facets.views-ajax']['js'] as $source => $options) {
        if (isset($replacements[$source])) {
          $new_js[$replacements[$source]] = $options;
        }
        else {
          $new_js[$source] = $options;
        }
      }
      $libraries['drupal.facets.views-ajax']['js'] = $new_js;
      $libraries['drupal.facets.views-ajax']['dependencies'][] = 'format_strawberryfield_views/modal-exposed-form-views-ajax';
      array_unshift($libraries['drupal.facets.views-ajax']['dependencies'], 'core/views.ajax');
  }
}
